version: "3.8"

services:
  debian-ssh:
    build: .
    container_name: debian-ssh
    user: "0:0"
    ports:
      - "2222:22"
    environment:
      # Используй ОДНО из двух:
      # 1) Безопаснее: хэш
      # ROOT_PASSWORD_HASH: "$6$XXXXXXXX$YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
      # 2) Или простой пароль (через PAM/chpasswd)
      ROOT_PASSWORD: "NEjr8VD2r1pBWZgXKua7"
    volumes:
      - ./authorized_keys:/root/.ssh/authorized_keys:ro
    restart: unless-stopped